### ISSUE TITLE
DisAlexi sending new estimates

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-disalexi#2]
@josue-medellin commented on [Tue Sep 06 2016](https://github.com/ssj-delta-cu/ssj-overview/issues/23)

USDA-ARS is sending new estimates due to an error. @qjhart Do we have an streamlined process for updating their estimates? Thanks, Josue

**Comment by qjhart** [comment]
@andybell, @josue-medellin this is probably the most complicated download of any of the supplied data.   That's because they supply daily data in individual files.  The steps are all documented in #1 and they really aren't that hard.  The biggest issue is having some google cloud storage to upload to data to.  I probably should have made this a Makefile, anticipating issues.  

Once uploaded, there is a EE script ssj-delta-cu/ssj-disalexi/daily_to_monthly.js to create the monthly data.  I'll assign @andybell , but I can help when the data comes if he has problems.

**Comment by josue-medellin** [comment]
Thanks Quinn. I feel a geek apprentice chatting in GigHub, out of necessity :-)

**Comment by qjhart** [comment]
@josue-medellin @andybell ,  The updated disalexi data is now available.  Something that I was reminded of uploading this data, and forgot, is that disalexi never sends us the water year, but only the 2015 calendar year, and their numbers should be removed for Oct,Nov,Dec on all the graphs

**Comment by andybell** [comment]
@qjhart - thanks! can you double check that the new asset in Earth Engine is shared with me? 

I'm getting a warning that `users/qjhart/ssj-delta-cu/ssj-disalexi/et_wy2015` is not found

**Comment by andybell** [comment]
Following up about disalexi for the calendar year - why does the asset still has 12 bands if there is no data for Oct - Nov? 

I think the easiest approach is to modify the EE JSON export to not run for Oct - Dec for disalexi. That way all the figures don't need to be manually modified.

**Comment by andybell** [comment]
@qjhart can you weigh in on the question about the missing months for Oct - Deect?

I've exported the new results for DisAlexi for the full 2015 wy as well as just Jan-Sept of 2015. However, since we are using the month name as keys for parsing the levels in the spreadsheet, all of the custom functions break when there is missing months. 

The errors are pointing toward this part of levels.gs (the same lines are used in a few places). 

TypeError: Cannot call method "forEach" of undefined.

```
var llist=levels[mon];
llist.forEach(function( ) {};
```

**Comment by andybell** [comment]
@qjhart I just saw the comment in the Google Doc - I think I've got a solution for this.

**Comment by qjhart** [comment]
@josue-medellin , @andybell , as I'm sure you've figured out, the data we have from them is Oct,Nov,Dec of 2015.  Hence the 12c bands. So, we probably shouldn't include it in the individual montlhly graphs.  However, I figured even though it's not accurate, if you want an estimate of the total yearly ET, it's the best we have, using 2015-1[012] in place of the 2014-1[012] data.   I did that so the scripts would stilll all run.  I guess I figured for Disalexi, you'd have to go in and modify the ranges that are used for those graphs.

**Comment by josue-medellin** [comment]
So, we would have to loose some of DisALEXI's charts?

**Comment by andybell** [comment]
@josue-medellin I've modified a version of the figures used in fig 7 to only include the months of Jan-Sept. What were you thinking of removing?

**Comment by andybell** [comment]
@josue-medellin All the work on this issue is done, the updated version of disalexi got incorporated.

Can you close this?

**Comment by josue-medellin** [comment]
I think is closed.

**Comment by josue-medellin** [comment]
@qjhart I do not see a button to close this.
